### ISSUE TITLE
CI for automatic release

### ISSUE THREAD

**Issue by DrSensor** [hql287/Manta#107]
Just curious, is there a reason for not using CI service for autorelease Windows and Linux version?

**Comment by hql287** [comment]
Not really, I just happen to use a Mac and haven't found an effective way to support both 3 at the moment. I tried VM but it slows down my machine significantly. 

But support for Windows and Linux is definitely on the list. Don't worry.

**Comment by mathieudutour** [comment]
you can use:
- travis to release on mac
- travis to release on linux
- appveyor to release on windows

Have a look at desktop/desktop to see how they are doing it

**Comment by hql287** [comment]
This is actually a development issue, not distribution. 

The main reason is that I don't have any machine running Windows or Linux so I don't know how it's gonna end up for these users. I tried VM but it doesn't work out very well. And I would feel much better with releasing Win/Linux version if I can test them out first.

Nonetheless, Windows/Linux support is definitely something that I want to do. So I'll get back to it once I have a better development setup.
