### ISSUE TITLE
Error when "Save as PDF"

### ISSUE THREAD

**Issue by rcorzogutierrez** [hql287/Manta#112]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [x] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [ ] macOS
- [x] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**
Windows 10 Fall Creators

**Describe your issue**

![screenshot 2018-01-02 15 17 52](https://user-images.githubusercontent.com/5765375/34498668-b4701008-efd0-11e7-8738-4eed2c4636b0.png)

**Comment by hql287** [comment]
Same as this? https://github.com/hql287/Manta/issues/110

**Comment by hql287** [comment]
OK, #109 introduced some changes in the way I store export path but I forgot to update it with the `saveAsPDF` script. Should be fixed in https://github.com/hql287/Manta/pull/114.
Thanks for reporting this 👍
