### ISSUE TITLE
Update Warning Message (Better UX)

### ISSUE THREAD

**Issue by hql287** [hql287/Manta#12]

**Comment by QuadDepo** [comment]
More information / screenshot on this?

**Comment by hql287** [comment]
Hi Ryan

Are you interested working on a PR for this?  Right now when you try to delete an invoice/contact, this warning message will show up.

![screen shot 2017-12-08 at 15 54 08](https://user-images.githubusercontent.com/2544327/33758234-0eb2d762-dc30-11e7-891f-828eb55ddc7d.png)

"Are You Sure" is bad. I would like to improve it a little bit. Something that's more meaningful but concise. [This article is pretty good](https://uxplanet.org/ux-writing-how-to-do-it-like-google-with-this-powerful-checklist-e263cc37f5f1), in my opinion.

**Comment by hql287** [comment]
@QuadDepo Are you interested working on a PR for this?

**Comment by QuadDepo** [comment]
Yea sure i can give it a try :)

**Comment by hql287** [comment]
Great!

**Comment by hql287** [comment]
This should be fixed with #187
