### ISSUE TITLE
Cannot read property 'currency' of undefined

### ISSUE THREAD

**Issue by juanpasolano** [hql287/Manta#135]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [x] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [X] macOS
- [ ] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

macOS High Sierra 10.13.2 (17C88)

**Describe your issue**

Followed [instructions to run the app locally](https://github.com/hql287/Manta#development) and I get this error on branch `dev`
```
Uncaught TypeError: Cannot read property 'currency' of undefined
    at Object../app/reducers/FormReducer.jsx (FormReducer.jsx:22)
``` 

**Steps to replicate**
Follow [instructions to run the app locally](https://github.com/hql287/Manta#development)

  
  **Other info**
node v9.3.0
npm 5.6.0
yarn 1.3.2

**Comment by hql287** [comment]
@juanpasolano I can't seem to replicate the issue. Are you using the newest code?

**Comment by hql287** [comment]
Ah, I think I know why it's happening. 

This seems to be related to #124 where some recent changes altered the way data is stored and the error occurred probably because your `appConfig` didn't have the key `invoice` key (it was added in  the #109 PR) 

Can you try pulling the newest code and re-run the app?

**Comment by juanpasolano** [comment]
```
$ git pull origin dev
From https://github.com/hql287/Manta
 * branch            dev        -> FETCH_HEAD
Already up to date.
```

**Comment by juanpasolano** [comment]
@hql287 I guess this was a false alarm I recloned the repo and run the instructions again and it worked perfectly.
I guess you can close this, I don't know what caused the issue
