### ISSUE TITLE
Application Not Opening in Windows 10 🤔

### ISSUE THREAD

**Issue by TechiePriyaRanjan** [hql287/Manta#137]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [x] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [ ] macOS
- [x] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

Eg: I'm using Windows 10 v1709

**After successful installation, I'm unable to proceed into the application; i.e I can't open the app. Have a look in the image(.gif) for more ** 😥

Eg:  

![2018-01-09_17h43_24](https://user-images.githubusercontent.com/11225491/34720739-d599812a-f565-11e7-81a6-03bd2e63566c.gif)

**Comment by c0b41** [comment]
#80

**Comment by hql287** [comment]
@TechiePriyaRanjan Hey, thanks for reporting this. It's a known bug as @c0b41 mentioned above and it's been fixed with https://github.com/hql287/Manta/pull/72 and will be included in the upcoming release on Jan 11.
