### ISSUE TITLE
Cannot Use it on Linux

### ISSUE THREAD

**Issue by hgabe** [hql287/Manta#142]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [ X] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [ ] macOS
- [ ] Windows
- [ X ] Linux

**Which is the version/distribution of the OS?**

Eg: I'm using Ubuntu 16.04.3

I start the app and cannot click the next during the intro nor does it let me skip the
introduction. I can't quit the app

**Steps to replicate**

Eg: 
1. Start app
2. try clicking next
3. Choose quit.

**Comment by hql287** [comment]
Hi @hgabe, thanks for reporting this. It's the same as https://github.com/hql287/Manta/issues/77
Hope this helps!

**Comment by Foriyo** [comment]
Application not start on ubuntu 20.04.2 LTS. I have download application from https://github.com/hql287/Manta/releases
