### ISSUE TITLE
[Bug] Can't edit invoice

### ISSUE THREAD

**Issue by huyphams** [hql287/Manta#159]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [X] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [X] macOS
- [ ] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

High Sierra

**Describe your issue**

Edit function on this screen doesn't work.

![screen shot 2018-01-13 at 2 13 12 pm](https://user-images.githubusercontent.com/3654622/34903844-666aa266-f86c-11e7-8c67-750fc8489b3d.png)

( and some minor bugs: after an upgrade, Manta didn't restart itself. When I restarted the app for the first time, the app can't display icons. but the second restart fixed all. Upgrade progress shows many float digits, Ex: 1.12412412125125159 %).

**Steps to replicate**
1. Open App.
2. Click on edit => nothing happened.

**Comment by hql287** [comment]
Hi Huy, thanks for the feedback! 👍

Yes, I noticed those issues and already working on it. 

I've filed an issue with the hiccup when upgrading the app, please track the current status here https://github.com/hql287/Manta/issues/149. Will tidy up the download progress percentage as well 😜

About editing invocies, I think @Venkat5694 is working on it here https://github.com/hql287/Manta/issues/57. Not sure what's the current status though. Let's wait for the update.
