### ISSUE TITLE
[Improvement] Support retina resolutions for logo

### ISSUE THREAD

**Issue by huyphams** [hql287/Manta#160]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [ ] It's a bug.
- [x] I'm requesting a new feature.

**Which version are you using?**

- [x] macOS
- [ ] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

High Sierra

**Describe your issue**

I tried to upload full HD image and some other resolutions but Manta always converts it to low resolution. I think we should support retina because it's a standard now.

**Steps to replicate**

- Upload logo in setting screen.
<img width="382" alt="screen shot 2018-01-13 at 2 31 48 pm" src="https://user-images.githubusercontent.com/3654622/34903975-c49b8ace-f86e-11e7-837e-fbdb61087174.png">

**Comment by hql287** [comment]
I really like your logo btw. I think you should make stickers for TablePlus, haha 😜

**Comment by hql287** [comment]
Closed in favour of #266
