### ISSUE TITLE
Integrate system Notification with autoUpdater

### ISSUE THREAD

**Issue by hql287** [hql287/Manta#165]
Show the [notification](https://electronjs.org/docs/tutorial/notifications) once the download is completed.

**Comment by hql287** [comment]
Fixed by #180

**Comment by AlphaStyle** [comment]
I forgot to say I got a beginning of a PR for this, basically you can disable/enable notifications in `settings/general` and the code would looks like this:
```js
import OSNotification from 'app/helpers/notification'
OSNotifciation(title, body)
```
Right now I am deciding whether to include the Manta Icon or the Company Icon you choose in `settings/profile`. Either way I have to figure out how to first read the image so I can use it for the notification. Scroll down a little to see the [Icon option](https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification) for HTML5 Notification.

**Comment by hql287** [comment]
> you can disable/enable notifications in settings/general

Nice 👍. I think I already added the notification helper with [this commit](https://github.com/hql287/Manta/pull/168/commits/bef9698df8ec9b634acb29dc24a87e20010abd20) Maybe we can try to reuse/refactor it? 

> Right now I am deciding whether to include the Manta Icon or the Company Icon you choose in settings/profile. Either way I have to figure out how to first read the image so I can use it for the notification. Scroll down a little to see the Icon option for HTML5 Notification.

It should always be Manta's icon as at the OS level, the user only needs to know which application just sent the notification. And this is already taken cared of by Electron.

Also, I noticed that there're a few helpers that we use across windows such as this one and the `center-on-primary-display.js`. I think we should have a shared folder called `helpers` in the project root for these helpers. Do you want to try refactoring this?

**Comment by AlphaStyle** [comment]
I didnt know about that commit :open_mouth: I have never done anything *preview* related so have never looked inside the `preview` folder :stuck_out_tongue: 

> Maybe we can try to reuse/refactor it?

Yes of course :slightly_smiling_face: 

> And this is already taken cared of by Electron.

Does the Manta icon appear by default when you get notified?
It does not for me when I run the development environment on linux (`yarn dev`, `yarn start`) :disappointed:

When I try to run `yarn build` and then `yarn dist:linux` it doesn't do the icons, I must do the `icns2png ...` command manually in the `build` folder to get the icons. But I have not tried this and then get notified, so I dont know whether the Manta Icon show by default or not.

> Do you want to try refactoring this?

Sure I can give it a try :slightly_smiling_face:
