### ISSUE TITLE
Merge contacts

### ISSUE THREAD

**Issue by mrbrianhinton** [hql287/Manta#166]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [ ] It's a bug.
- [X ] I'm requesting a new feature.

**Which version are you using?**

- [X ] macOS
- [ ] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

I'm using macOS High Sierra

**Describe your issue**

When create a new invoice, and using the same name, and business it would be nice if the contact, and business information could be auto-filled based on previously created invoices. That way a new contact isn't created each time.

**Steps to replicate**

NA

**Comment by hql287** [comment]
@mrbrianhinton Actually, you can. 

![Select Contact](https://d2ffutrenqvap3.cloudfront.net/items/1c0a3E3k221d2W0e1b3H/Select%20Contact.gif?v=0cdc9db3)

**Comment by mrbrianhinton** [comment]
Ahhh. That wasn't at all obvious. Even though clearly it is. My request still stands. Having it source the database of contacts, and autofill would be a better overall experience.

PS. Sounds 👍
