### ISSUE TITLE
[Improvement] Improve auto-update behaviour

### ISSUE THREAD

**Issue by huyphams** [hql287/Manta#170]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [X] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [X] macOS
- [ ] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

High Sierra

**Describe your issue**

- Manta should not show auto-update popup when there is no update available.

**Steps to replicate**

- I'm not sure how to reproduce this bug, but I just opened the app and it showed.
- I think it's better if Manta hides the popup when it checks for update itself (only show when user check for update or there is an update available).

<img width="571" alt="screen shot 2018-01-16 at 4 18 24 pm" src="https://user-images.githubusercontent.com/3654622/34981123-2b5fc664-fad9-11e7-81fa-8df1ad87051c.png">

**Comment by hql287** [comment]
Hi Huy, you're right! 

It should only show if there's a new update. Will add this to the next release. 👍

In the meantime, please make Manta check for update only once a week. 

![](https://d2ffutrenqvap3.cloudfront.net/items/0a0l3b0l2o2p2O2O1W0K/cheng-check-for-update.gif?v=b86e131e)
