### ISSUE TITLE
2-decimal formatting?

### ISSUE THREAD

**Issue by dooleysworne** [hql287/Manta#173]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [ ] It's a bug.
- [X] I'm requesting a new feature.

**Which version are you using?**

- [ ] macOS
- [X] Windows
- [X] Linux

**Which is the version/distribution of the OS?**
I have been using Manta 1.1.1 on a Windows 10 laptop and on a Linux Mint 18.2 Sonya laptop.

**Describe your issue**
First of all, I must compliment you on a superb application. I have only one request: When certain purchase amounts are entered (such as $25.00 and $12.50 for instance), the values are printed as $25 and $12.5.  Is it possible to maintain a 2 decimal format for values in the invoices?

Thanks for your consideration. I really like this application.

**Steps to replicate**
[None]

**Comment by davidsommer** [comment]
I think that would be an awesome Feature. I woud add the following Settings under Invoicing / Currency:

1. Decimal Format ( example 2 -> forcing all amounts to be printed 25.00)
2. Show currency before / after the amount (some currencys are printed after the amounts)
