### ISSUE TITLE
on startup bug selectedTextBackgroundColor

### ISSUE THREAD

**Issue by keyeMyria** [hql287/Manta#179]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [ ] It's a bug.

**Which version are you using?**

- [ ] macOS
When i start up by npm run start , the console log out "Electron Helper[1584:20104] Couldn't set selectedTextBackgroundColor from default ()".
It there any idea?

**Comment by hql287** [comment]
Hey @keyeMyria, thanks for reporting this. 
I noticed this but it seems to be harmless. Do you want to work on a PR for this? ;)

**Comment by hql287** [comment]
[This's actually related to Chromium and can be safely ignored](https://github.com/electron/electron/issues/4420#issuecomment-222393384)
