### ISSUE TITLE
Extra scroll bars on Windows

### ISSUE THREAD

**Issue by tbow** [hql287/Manta#182]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [X] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [ ] macOS
- [X] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**
Windows 10 1607

**Describe your issue**

Double scroll bars for main app window and dialog boxes

**Steps to replicate**

Eg: 

1. Open App in windows
2. View application 
3. Change setting that has dialog box
4. View dialog box
![capture1](https://user-images.githubusercontent.com/1908038/35164871-c2e096dc-fd11-11e7-83f1-5b64a0a6270f.PNG)
![capture2](https://user-images.githubusercontent.com/1908038/35164872-c2edadf4-fd11-11e7-9fe8-033e462bd6ef.PNG)
![capture3](https://user-images.githubusercontent.com/1908038/35164873-c2f9dc6e-fd11-11e7-8a52-654cedc95b6b.PNG)

**Comment by hql287** [comment]
Hi Troy, thanks for reporting this. It's a known issue and being worked on.

**Comment by jens-t** [comment]
This happens on linux too. if the previewer window is big enough they disappear, so it is probably a css bug. i see if i can find a fix.

**Comment by hql287** [comment]
Sorry, I kept forgetting about this. And yes, it's definitely a CSS bug. Thanks for looking into this 👍

**Comment by jens-t** [comment]
Yeah, looks like a padding is added to the height, a simple border-box should do it. If im right.

**Comment by jens-t** [comment]
#236 should fix the problem :)
