### ISSUE TITLE
32 Bit Version

### ISSUE THREAD

**Issue by remyscherer** [hql287/Manta#185]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [ ] It's a bug.
- [X ] I'm requesting a new feature.

**Which version are you using?**

- [ ] macOS
- [ X] Windows
- [ ] Linux

Is it possible to release a 32Bit Version?

**Comment by hql287** [comment]
Hey @remyscherer, 

[Looks like this is possible](https://github.com/electron/electron/blob/master/docs/tutorial/supported-platforms.md). Have you tried the Windows installer in the releases tab yet?

**Comment by remyscherer** [comment]
Hey @hql287 ,
thanks for your quick reply.

I tried to install it with the setup.exe from 1.1.2, but it tells me that 64-Bit is required.
I have windows 7 Home Premium & my processor is AMD-FX6100 Six-core.
Do I need to install something from electron itself?

Thank you :)

**Comment by hql287** [comment]
@remyscherer: The doc states that:

> Please note, the ARM version of Windows is not supported for now.

Do you know if your processor is ARM or x86? Also, you should not need to install anything to make it work.

**Comment by remyscherer** [comment]
I can't figure this out.. But I have Atom installed, which is also electron and works.

**Comment by hql287** [comment]
@remyscherer Can you share a screenshot of the error? I'll investigate this. Thanks!

**Comment by remyscherer** [comment]
![mantaerror](https://user-images.githubusercontent.com/27846555/35765628-4d13fa08-08c8-11e8-9c70-58441a655f04.png)

It only says: 64-Bit-Windows is required
I use the windows installer 1.1.2 .exe

Thanks for checking! :)

**Comment by remyscherer** [comment]
Still doesn't work on 32-Bit

**Comment by hql287** [comment]
@remyscherer: Fixed with #278. I think I [found the culprit](https://www.electron.build/configuration/win#WindowsConfiguration-target). 

The next release of Manta will include this by default. If you want to try it out now (which would be nice), you can run this to build the Windows installer: 

```
yarn release:win
```
