### ISSUE TITLE
Customizable decimal separator

### ISSUE THREAD

**Issue by DarkSmile92** [hql287/Manta#190]
**Is it a bug or a feature request?**

- [ ] It's a bug.
- [x] I'm requesting a new feature.

**Which version are you using?**

- [ ] macOS
- [x] Windows
- [x] Linux

**Which is the version/distribution of the OS?**

Windows: Windows 10 Fall Creators Update
Linux: Ubuntu 17.10

**Describe your issue**

Most european countries use a comma (,) as decimal separator and not a dot (.).
It will be great to have a setting to choose the decimal separator.

**Steps to replicate**
- Enter amount on invoice
- Print / Preview invoice

**Remarks**
I will submit a PR this week to implement this.

**Comment by hql287** [comment]
Good idea, this would be very handy! 👍 
Seem to be related to https://github.com/hql287/Manta/issues/173 btw.

**Comment by DarkSmile92** [comment]
@hql287 yes just saw it, will implement both in one rush :)

**Comment by DarkSmile92** [comment]
Found a nice solution with `toLocaleString()` which takes region specific settings to solve this and #173 with one commit.
When given a locale, it replaces comma and dot accordingly to the region. No other settings needed.
Passing `minimumFractionDigits` and `maximumFractionDigits` with value *2* returns always 2 fractions.

See PR.

**Comment by DarkSmile92** [comment]
@hql287 I checked the behavior and need your advice :grinning:
Right now the function to format numbers uses `appConfig.get('general.language')` to get the locale and this will determine the separator.
If I implement a new parameter to choose between comma and dot as decimal separator, I need to overwrite the locale setting in favor to have correct formatted numbers.

So this issue will be solved by the locale thing as the app will be translated and have a language setting later. The decimal separator will be correct by default then because of the locale setting.

Only possible exception would be when my locale is german for example (comma separator) and I will bill to an US / english customer. But normally they accept it this way.

If you agree, I won't add a parameter for this to settings and the decimal separator will be determined by the locale.
What are your thoughts on this?

**Comment by DarkSmile92** [comment]
@hql287 Wow that is what I call a good answer! :grin:
From that point of view it totally makes sense. So I will implement the settings for comma and dot on this PR. Like you mentioned a separate PR for storing the values on the settings record is better to keep clear lines.

I will hurry up committing the rest of this PR.

**Comment by hql287** [comment]
So while working on this, I discovered another issue which is when the decimal separator is the same with thousand separator. 

For example, `1,999.99` would become `1,999,99` which doesn't make sense. According to this [International Language Environments Guide from Oracle](https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html), there are only 3 cases:

| Sample Number          | Thousand Separator | Decimal Separator |
|----------------------|--------------------- |---------------------|
|  1,234,567,890.000   |   Comma (,)               | Dot (.)                       |
|  1.234.567.890,000   |   Dot (.)                      | Comma (,)                |
|  1 234 567 890.000   |   Space ( )                  | Dot (.)                       |

The `decimal fraction`, on the other hand, can be `0`, `2` or `3` without causing any real issue. So I'm proposing to either: 

- Change `dicimalSeparator`field to `numberSeparator` with options such as `commaDot`,  `dotComma`, and `spaceDot`
- OR, keep `dicimalSeparator` and add `thousandSeparator` field. But this approach would make the validation more complicated, though.

Let me know what you think.

**Comment by hql287** [comment]
Also, if you look at my commits, you'll see that these settings are grouped under `currency` and I think this should be implemented like `tax`. This means the currency field in Form page will also have these options. 

So yeah, I think it would be a bit more work than we expected. Please let me know if you would like to finish the PR 😜

**Comment by hql287** [comment]
@DarkSmile92: Just wanted to let you know that I already started working on the second issue and probably will finish this PR as well. Feel free to fix another issue is you have time. 

Thanks :)
