### ISSUE TITLE
[Bug] Manta can't update itself

### ISSUE THREAD

**Issue by huyphams** [hql287/Manta#193]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- It's a bug.

**Which version are you using?**

- macOS

**Which is the version/distribution of the OS?**

- macOS High Sierra

**Describe your issue**

- Can't update

![screen shot 2018-01-26 at 3 05 06 pm](https://user-images.githubusercontent.com/3654622/35430367-8cc57a60-02aa-11e8-850f-eb6de5df3e08.png)
![screen shot 2018-01-26 at 3 04 57 pm](https://user-images.githubusercontent.com/3654622/35430370-8ed9bf82-02aa-11e8-87f6-cb50f1d1970b.png)

** Minor issue**

- Update progress still showing many float digits.
- The app can't restart itself.

**Steps to replicate**

- Open app.
- Click on Update.
- When the update is downloaded => click on restart => nothing.
- Click on the app icon on dock => choose quit => Manta restarts itself.
- Click on check for update => there is still have a new update available but can't update. see the image above.

Update:
- After restarting the app one more time, everything works as expected.

**Comment by hql287** [comment]
@huyphams: You still experienced this because Manta had to use the old mechanism in v1.1.1 to upgrade to v1.1.2. Once you have v.1.1.2, this problem should go away with all future updates (v.1.1.3 and later). 

Please report again if it persists. Thanks! :)
