### ISSUE TITLE
Error on startup v1.1.2

### ISSUE THREAD

**Issue by twmbx** [hql287/Manta#196]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**
- [x] It's a bug.

**Which version are you using?**
- [x] Linux

**Which is the version/distribution of the OS?**
Elementary OS ( Ubuntu 16.04 )

**Describe your issue**
App experiences error on startup

**Steps to replicate**
Launch Manta
![screenshot from 2018-01-27 22 02 45](https://user-images.githubusercontent.com/536306/35475867-9811b83e-03ae-11e8-95fd-02ddbc4b65d3.jpeg)

**Comment by hql287** [comment]
Hey Twaambo Haamucenje, sorry for taking a bit long to get back to you. Can you try to run the dev server and see if there's anything in the console?

**Comment by hql287** [comment]
Close due to inactivity.
