### ISSUE TITLE
Win 8 

### ISSUE THREAD

**Issue by Chorcai** [hql287/Manta#198]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

-  It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [ ] macOS
-  Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

Win8 Pro (app running as Win7)

**Describe your issue**
When entering details, app returns an "UNKNOWN ERROR" it appears not to be able to save the description text. 

Irish VAT rate is 13.5% can this be causing an issue?

**Steps to replicate**

Eg: 
1. Right click on the Dock icon 
2. Choose quit.

**Comment by hql287** [comment]
Hey @Chorcai: I just tried using an odd tax amount (eg 10.5%) and it's working as expected. Does the error appear _while_ you're typing or when you open the app? Thanks again for reporting this.

**Comment by hql287** [comment]
Close due to inactivity
