### ISSUE TITLE
Portable Version for Windows?

### ISSUE THREAD

**Issue by hezral** [hql287/Manta#199]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [ ] It's a bug.
- [X] I'm requesting a new feature.

**Which version are you using?**

- [ ] macOS
- [X] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

Eg: I'm using macOS Sierra
Windows 7

**Describe your issue**

Eg: I can't quit the app
Not really an issue. Hoping there is a non-exe option for use on controlled workstation where we don't have admin rights to install. 

**Steps to replicate**

Eg: 
1. Right click on the Dock icon 
2. Choose quit.

**Comment by hql287** [comment]
Hey @hezral: [I think it's possible](https://www.electron.build/configuration/win). Will export the portable version in the upcoming release. Please let me know if this work.

**Comment by hezral** [comment]
Thanks!
