### ISSUE TITLE
Tour layout

### ISSUE THREAD

**Issue by erudman21** [hql287/Manta#202]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [x] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [ ] macOS
- [x] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

Windows 10

**Describe your issue**

Unnecessary scrollbar and part of slide image showing underneath slider for multiple slides in the tour.  Only part of the 'next' and 'skip' buttons are clickable for these slides as well.

Ex: 
![screenshot 5](https://user-images.githubusercontent.com/26533234/35761692-7c04205a-0859-11e8-9275-ee3ec02e438d.png)

I think the issue could be fixed by adding overflow hidden to the Wrapper styled component.

**Comment by hql287** [comment]
@erudman21: Omg this looks terrible!! Thanks for reporting this. WIll fix soon!

**Comment by hql287** [comment]
Fixed with #236
