### ISSUE TITLE
German date notation

### ISSUE THREAD

**Issue by marcobischoff** [hql287/Manta#211]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [ ] It's a bug.
- [ x ] I'm requesting a new feature.

**Which version are you using?**

- [ x ] macOS
- [ ] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**
macOS High Sierra

**Describe your issue**
As in the future there will be the german language added, it would be great to have the german notation of date (eg. DD.MM.YYYY)

**Comment by hql287** [comment]
Fixed with #214
