### ISSUE TITLE
Feature Request: Reporting Interface

### ISSUE THREAD

**Issue by Dan458** [hql287/Manta#219]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [ ] It's a bug.
- [x] I'm requesting a new feature.

**Which version are you using?**

- [x] macOS
- [ ] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

I'm using macOS High Sierra

**Describe your Feature**

It would be great if there was a reporting interface, reporting on things such as best sellers, the client that has spent the most over a time period etc.

**Comment by rcorzogutierrez** [comment]
Hi
This request is similar #106 , check it.

**Comment by Dan458** [comment]
Yes it is. Just noticed that it has already been raised.

**Comment by hql287** [comment]
Thanks! @rcorzogutierrez
