### ISSUE TITLE
Can't remove discount when editing

### ISSUE THREAD

**Issue by IL4Miy** [hql287/Manta#227]
**Is it a bug or a feature request?**

- [x ] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [x ] macOS
- [ ] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

I'm using macOS High Sierra

**Describe your issue**

I can't remove the discount field after creating an invoice with discount.

**Steps to replicate**

1. Create a new invoice with discount. (I choose 10%)
2. Edit the invoice and disable the discount field.
3. Klick "update"
4. View the invoice, but the discount is still there.

**Comment by hql287** [comment]
@IL4Miy : Thanks for reporting the issue, I'm fixing it right now!

**Comment by hql287** [comment]
Ok, found the culprit. The current implementation of updating a doc will merge the current doc with the new data so all existing key will remain in the doc. It's an easy fix and will be included in the release tomorrow.
