### ISSUE TITLE
internationalize dates

### ISSUE THREAD

**Issue by jens-t** [hql287/Manta#239]
The format of the dates is not translated yet. To change this i looked into the code and thought a bit about it and came up with the following todos:

- set locales for moment.js (@hql287 saw you already did this, not sure yet if it is globally available this way, will check)
- refactor form field "Settings -> Invoice -> Other -> Date Format" options
- use locale for form field "Create A New Invoice -> Due Date" format

**Anything else to consider?**

Would add a pull request for this feature ... **ok?**

**Comment by hql287** [comment]
Wait, what's your question again? 😅

**Comment by jens-t** [comment]
I updated the issue description and marked the questions :laughing: better? :see_no_evil:

**Comment by jens-t** [comment]
I make a PR, then it's maybe more clear what i mean.

**Comment by jens-t** [comment]
Closing here ... continued in #247
