### ISSUE TITLE
Missing translation for invalid custom invoiceID validation

### ISSUE THREAD

**Issue by hql287** [hql287/Manta#243]
![screen shot 2018-03-02 at 23 58 24](https://user-images.githubusercontent.com/2544327/36911273-9da86694-1e75-11e8-938f-e1d249d03313.png)

**Comment by hql287** [comment]
Just added the missing keywords to Crowdin, now waiting for the translation.

**Comment by hql287** [comment]
@jens-t Can you add the missing translation for German? Thanks! :)

**Comment by jens-t** [comment]
the missing german translation is already complete on crowdin, and i would approve it :)

**Comment by hql287** [comment]
@jens-t Thanks, I just approved them and saved you the trouble! :D

**Comment by hql287** [comment]
Fixed with #249
