### ISSUE TITLE
Can't change language without setting tax amount greater than zero first

### ISSUE THREAD

**Issue by romainwn** [hql287/Manta#273]
## Expected Behavior
When I launch the app, I should be able to switch language without doing anything else

## Current Behavior
When starting the app for the first time, Tax amount is set to zero.
So, I get an "Invalid tax" error while just trying to switch language.

## Possible Solution
- Set a save button for each tab
- Set a default tax value greater than zero

## Steps to Reproduce (for bugs)
1. Launch app for the first time
2. Go to Settings -> General 
3. Switch language to whatever language
4. Click on the Save button

## Context
Just discovered this app and would love to contribute !
I just started the app in dev mode for the first time, wanted to check in the options and switch language, but then when I wanted to save, I got the "invalid tax" warning.

## Your Environment
* Version used: 1.1.4
* Operating System and version: macOs High Sierra 10.13.3

**Comment by romainwn** [comment]
How to reproduce if the app already installed : 
- Set tax amount to 0 in the Settings (located in ~/Library/Application Support/Manta/Settings on macOs)
- Start the app and try to change language 
- Click save button

**Comment by hql287** [comment]
Yes, you can't save the settings when the tax amount is equal or less than zero. This is the default value for the tax field if you decide to use it in the form. So just it to something greater than 0 and you're good to go.
