### ISSUE TITLE
export pdf and save configs button out of their boxes

### ISSUE THREAD

**Issue by romainwn** [hql287/Manta#274]
## Expected Behavior
<img width="1018" alt="screen shot 2018-03-20 at 22 18 37" src="https://user-images.githubusercontent.com/13620579/37683364-aec73f8e-2c8c-11e8-9dbb-476f28fcfbab.png">

## Current Behavior
<img width="1018" alt="screen shot 2018-03-20 at 22 15 26" src="https://user-images.githubusercontent.com/13620579/37683286-6b318b1c-2c8c-11e8-8658-75a956455f6a.png">
If I want the expected behavior, I need to resize the window until I get the expected behavior

## Possible Solution
- Set a higher minHeight
- vertical scroll bar ?

## Steps to Reproduce (for bugs)
1. Create a new invoice
2. Click Save & Preview

## Context
Launching the app for the first time, and trying to create an invoice

## Your Environment
* Version used: 1.1.4
* Operating System and version: macOs High Sierra 1.13.3

**Comment by hql287** [comment]
Thanks for reporting this. It's already fixed with this PR: https://github.com/hql287/Manta/pull/257
