### ISSUE TITLE
Allow taxes to be 0%

### ISSUE THREAD

**Issue by pablopunk** [hql287/Manta#282]
I didn't find this question in any other issue:

## Expected Behavior

I want to set the taxes to 0%. I deal with clients out of my country and I can't charge them taxes (tho they have to be 0%)

## Current Behavior

I can't save any setting with a tax value of 0%

## Possible Solution

Allow 0%!

**Comment by hql287** [comment]
@pablopunk: Have you tried turning off the Tax field in the form? (Making it not required for creating the invoice)

**Comment by pablopunk** [comment]
@hql287 Okay thanks, I guess I can do that.

Although I still think it's a bad experience to have taxes set to 0 by default because I opened the app for the first time, changed my name in Settings and trying to save, it told tax should be more than 0 (which I didn't touch).

**Comment by hql287** [comment]
@pablopunk: Agree, it's kind of annoying! Will fix soon 👍
