### ISSUE TITLE
Issue while building Manta from source

### ISSUE THREAD

**Issue by cryptobench** [hql287/Manta#305]
I've tried following the yarn guide to installing and everything is fine working except when i'm trying to compile it. I'm getting the issue that electron-builder 3.0.3 is recommended but there's no version 3.0.3 of electron-builder. I've checked the website and others versions don't work for me.

**Comment by defkev** [comment]
Not builder but updater is recommended for the version used.

Change `"electron-updater": "^2.21.0"` to `"electron-updater": "^3.0.3"` in `package.json`
