### ISSUE TITLE
Support for Indian Rupee Symbol

### ISSUE THREAD

**Issue by Navneet-Suresh** [hql287/Manta#325]
### Prerequisites

- We realize there is a lot of data requested here. We ask only that you do your best to provide as much information as possible so we can better help you.
- Read the [contributing guidelines](https://github.com/hql287/Manta/blob/dev/.github/CONTRIBUTING.md).
- Ensure the issue isn't already reported.
- Should be reproducible with the latest version of Manta.
Yes, I am using Latest version as of 16-09-19(DD-MM-YY)

## Expected Behavior

I would like to request you to add support for Indian Rupee **Symbol: ₹**

## Current Behavior

Currently it shows Rs.

## Steps to Reproduce (for bugs)

1. Set INR as Default Currency.
2. Create an Invoice
3. Add a sample product
4. It will show **Rs** instead of **₹** Symbol.

## Context

* Version used:
* Operating System and version:
Latest Version: v1.1.4 on Windows 10 Pro

**Comment by sasivarnan** [comment]
@Navneet-Suresh I guess this is fixed in #285. But haven't made a release after incorporating this fix. 

@hql287 Any plans of releasing a new version with this new fix?

**Comment by Navneet-Suresh** [comment]
Implemented in #285. CLosing this issue.
