### ISSUE TITLE
Crash on Startup due to electron version (Harfbuzz version)

### ISSUE THREAD

**Issue by JorisM** [hql287/Manta#346]
### Prerequisites
When I try to run Manta on Fedora 31, it crashes on startup with the following error: 

```
(manta:40935): Pango-ERROR **: 09:48:13.186: Harfbuzz version too old (1.4.2)
```

## Expected Behavior

the application should start

## Current Behavior

it crashes

## Possible Solution

according to this issue https://github.com/electron/electron/issues/20348#issuecomment-542150507 an upgrade of electron is required to fix this. 

## Steps to Reproduce (for bugs)

1. download fedora 31 image
2. download AppImage on github releases page
3. chmod +x ./Manta-1.1.4-x86_64.AppImage
4. ./Manta-1.1.4-x86_64.AppImage

## Your Environment

* Version used: 1.1.4
* Operating System and version: Fedora 31

**Comment by SWW13** [comment]
```
yarn upgrade electron
```
fixes the issue

**Comment by m0ngr31** [comment]
Same issue here.

**Comment by nknganda** [comment]
Same issue on Ubuntu 20.04.1 LTS

**Comment by kevinmukuna** [comment]
@nknganda did you manage to get around this?
