### ISSUE TITLE
`yarn release:linux` needs system dependencies

### ISSUE THREAD

**Issue by crabmusket** [hql287/Manta#46]
I tried running `yarn release:linux` and found I had to install a few additional dependencies. I was running in the `node:8` Docker container based on Debian, so:

```
apt update
apt install -y icnsutils graphicsmagick
```

`icnsutils` is for the `icns2png` command, and `graphicsmagick` provides `gm`.

Not sure if you want to document this anywhere, but hopefully other Linux users will find this :).

**Comment by hql287** [comment]
Hey Daniel, 

Thanks for reporting this. 
I'll add it to the doc. 

Cheers!

**Comment by hql287** [comment]
Actually, scratch that. Would you be able to work on a PR for this? I guess you would articulate the issue/solution better since you're already working on Linux?

**Comment by crabmusket** [comment]
I'll do it tomorrow :)
