### ISSUE TITLE
Cannot drag to select in text fields

### ISSUE THREAD

**Issue by OzairP** [hql287/Manta#47]
Trying to drag to select in text fields moves entire app.

Video: https://static.ozairpatel.com/u09sl.mp4

**Comment by hql287** [comment]
Hey @OzairP , 

Sorry for the inconvenience but this would be a quick fix. 
In the meantime, you can use `CMD+A` to select all or using Shift with arrow keys to partially select the text.  

Thanks for reporting this.

**Comment by hql287** [comment]
Fixed in https://github.com/hql287/Manta/pull/56.
