### ISSUE TITLE
unable to resize preview window

### ISSUE THREAD

**Issue by peonmodel** [hql287/Manta#48]
on Macbook Pro 15" the preview window is too long and the "save as pdf" button is cut off
the window is also not resizable or able to zoom out to see the entire page

**Comment by hql287** [comment]
Hey @peonmodel 

The `previewWindow` is actually resizable but it also has a minimize size. What's your screen's resolution? Can you attach a screenshot?

**Comment by peonmodel** [comment]
<img width="1280" alt="cutoff" src="https://user-images.githubusercontent.com/12645203/33749929-a83733e4-dc0b-11e7-8b24-2d86a0381595.png">

this is how it appears on Retina, 13-inch, Early 2015 (turns out it wasnt 15" but 13") (2560-by-1600 native resolution)

it wasnt captured in the screenshot but when i positioned my cursor to the corner of the window, it changed to the horizontal resize cursor instead of the diagonal resize cursor, positioning the cursor to the top edge did not change the cursor

<img width="1280" alt="fullscreen" src="https://user-images.githubusercontent.com/12645203/33749930-a866aec6-dc0b-11e7-89a9-87b2ea085ad7.png">
this is screenshot when i set it to fullscreen mode, the "save as pdf" button is still cutoff

**Comment by hql287** [comment]
Ok, got it! I guess I'll just need to remove the minimum window screen then you'll be good to go.

**Comment by hql287** [comment]
Fixed in https://github.com/hql287/Manta/pull/56

**Comment by MaloRchrd** [comment]
Same issue on MBP 13"

**Comment by hql287** [comment]
@MaloRchrd : It's fixed in #56 (will be in v.1.1.0). The minimum size of the `previewWindow` is now `1024x800` and should fit most modern screens.
