### ISSUE TITLE
alignment of numeric values should be to the right

### ISSUE THREAD

**Issue by peonmodel** [hql287/Manta#51]
as per UX custom: https://ux.stackexchange.com/questions/24066/what-is-the-best-practice-for-data-table-cell-content-alignment

numeric values like money and quantities are aligned to the right when displayed in tabular form

it is easier on the eye when summing up the values

currencies should also be displayed with fixed decimal points, for dollars 2 decimal places

it would also be great it the font family can be changed

**Comment by hql287** [comment]
Awesome @peonmodel Keep 'em coming :)

**Comment by hql287** [comment]
Fixed with #120
