### ISSUE TITLE
Missing font? 

### ISSUE THREAD

**Issue by hql287** [hql287/Manta#55]
Looks like Manta doesn't display the font correctly. Can anyone confirm this? 

Here's what it looks like on my machine. 
![screen shot 2017-12-09 at 15 02 10](https://user-images.githubusercontent.com/2544327/33793864-8b6340e0-dcf2-11e7-96dd-ef048fcec2df.png)

**Comment by jyounus** [comment]
Same here. Thought it was intentional. The business template works fine.

Would be cool to allow selecting a completely custom font for everything on the page. Maybe as a drop down on the right hand side?

**Comment by hql287** [comment]
@jyounus Thanks for the confirmation. This looks like relative paths issue, will investigate tmr.
Yes, I was thinking about the using custom fonts feature, too. Might take some time to figure out the design though. But thanks for the suggestion.

**Comment by hql287** [comment]
Fixed in https://github.com/hql287/Manta/pull/98. Thanks to Juan @jiserra 👍

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/72659799-4e17b480-39bd-11ea-94b6-6245e7979c52.png)
This still seems to be an issue on Windows 10 with the latest build installed
