### ISSUE TITLE
Allow to edit invoices

### ISSUE THREAD

**Issue by SkyzohKey** [hql287/Manta#57]
Currently if I spot a typo fix on an invoice, I'm forced to create a new one.
We could have 2 options in addtion to see/delete like : Edit, Duplicate.

:)

**Comment by hql287** [comment]
Got to admit that I ran into this sometimes too. And it's kind of annoying. 
Let's see if it's easy enough to make it to v.1.1.0

**Comment by Venkat5694** [comment]
@hql287 I saw that the dev build now has an edit button on each invoice. If you haven't already started it, can I pick this one up given #65 isn't something that I can work on.

**Comment by hql287** [comment]
Yes, that would be great! Thanks.

**Comment by hql287** [comment]
@Venkat5694 Would you be able to finish this before Jan 11? I would like to include this in the V1.1 since #124 will introduce some changes to the current docs (eg Tax ID) and I think people would like to update their invoices after this.

**Comment by Venkat5694** [comment]
I'll try and get a PR in by 10th but I don't think I can get it in any earlier.

**Comment by hql287** [comment]
@Venkat5694 That works for me. Thanks! 👍

**Comment by hql287** [comment]
@Venkat5694 Any update on this? :)

**Comment by huyphams** [comment]
Hey @hql287 I think we should put an alert `coming soon` in incomplete function. Then everybody knows it is not complete => not report it as a bug.

**Comment by hql287** [comment]
> Hey @hql287 I think we should put an alert coming soon in incomplete function. Then everybody knows it is not complete => not report it as a bug.

True! 👍  It's actually my bad, I overlooked this, probably should have hidden the edit button.

**Comment by johnhorsema** [comment]
Just used Manta for my first invoice! Sad to find I can't edit the invoices. Thanks for adding the button, but I agree to put "WIP" or "coming soon" to tell users the button does not work.

**Comment by hql287** [comment]
@johnhorsema Sorry for the confusion, this will be fixed in the next release

**Comment by hql287** [comment]
Ok, https://github.com/hql287/Manta/pull/172 fixed this. You'll be able to edit your invoices with v1.1.2 which will be released this Friday. Enjoy!
