### ISSUE TITLE
Remove ugly double scrollbars

### ISSUE THREAD

**Issue by SkyzohKey** [hql287/Manta#60]
An image is worth thousands words. Scrollbars should only appears if user is able to scroll content.

![](https://0x0.st/sHdB.png)

**Comment by jmrodriguesgoncalves** [comment]
Can I give this a try?

**Comment by hql287** [comment]
Go for it @jmrodriguesgoncalves!

**Comment by hql287** [comment]
@SkyzohKey Are you using Linux or Windows?

**Comment by jmrodriguesgoncalves** [comment]
Awesome thanks! I am using Windows

**Comment by hql287** [comment]
Hey @jmrodriguesgoncalves, Some people told me that they couldn't get pass the Welcome windows when they're using Windows. Did this happen to you, too?

**Comment by jmrodriguesgoncalves** [comment]
I'm setting up a testing environment to give it a shot. When running yarn release:win, I get this message:

> yarn run v1.3.2
$ webpack --env.production
module.js:471
    throw err;
    ^
Error: Cannot find module 'webpack-merge'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Joao\Desktop\SchoolWork\Year5\Semester1\DPS9
09\Manta\webpack.config.js:3:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

I've already made sure to have webpack installed, did it both globally and locally, and I've already made sure it was added to my Path

**Comment by hql287** [comment]
Actually, `webpack-merge` is something else, not the `webpack` package itself. 
Did you install all dependencies (`yarn install`) before running the release command?

**Comment by jmrodriguesgoncalves** [comment]
I did before with no issues, but now when doing it again it seems to run into trouble:

> yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error electron-builder@19.45.5: The engine "node" is incompatible with this modu
le. Expected version ">=6.11.4".
error Found incompatible module

**Comment by jmrodriguesgoncalves** [comment]
Yup seems like I  won't be able to help much. Just like you said, can't get past the welcome screen.

**Comment by SkyzohKey** [comment]
I'm using Linux. The welcome screen also is broken for me, because of draggableness. Should be fixed by #66 :)

**Comment by hql287** [comment]
@SkyzohKey Did you make a build with #72 already?

**Comment by hql287** [comment]
@jmrodriguesgoncalves Try this tip from @SkyzohKey: Press `Tab + Enter`

**Comment by jmrodriguesgoncalves** [comment]
@hql287 @Skyzohkey that actually did it, I was able to get to the program. Now, I was trying to setup the development environment, however I ran into this after doing yarn run on one of the two terminals:
![image](https://user-images.githubusercontent.com/14240261/33857319-254f9eae-de99-11e7-8bab-470070c308e5.png)
Could this have something to do with my local permissions?

**Comment by SkyzohKey** [comment]
Or you have something else listening on :8888. Try to run `lsof -i :8888` :)

**Comment by hql287** [comment]
Merged https://github.com/hql287/Manta/pull/72
