### ISSUE TITLE
more flexibility for VAT and contacts

### ISSUE THREAD

**Issue by mathieudutour** [hql287/Manta#63]
**Is it a bug or a feature request?**

- [ ] It's a bug.
- [x] I'm requesting a new feature.

**Describe your issue**

I'm often billing with a `VAT: charged reversed`. That's impossible in Manta, you can only enter a number. It would be nice to be able to enter anything and default to `0` if you can't parse it properly.

More generally, it would be nice to be able to have more flexibility in everything. For example, one of my clients wants the contact section to be
```
{{name of the company}}
VAT: {{VAT number}}
{{address}}
```
Maybe there could be a text area with a mustache type of template where we can specify what are the fields we care about the contact?

**Comment by hql287** [comment]
@mathieudutour : Is`VAT: charged reversed` a common thing in Europe? Can you explain how it works? Does this mean the tax value would be 0, meaning the invoice does NOT include tax and the clients would need to do the tax themselves?

**Comment by mathieudutour** [comment]
I don't know how common it is in the grand scheme of things but it's what I use most commonly yes.

Yes that's it (that's why it should default to 0 if we cannot parse to a float).

**Comment by hql287** [comment]
Thanks, moved this to https://github.com/hql287/Manta/issues/90
