### ISSUE TITLE
mark invoices as "paid"

### ISSUE THREAD

**Issue by mathieudutour** [hql287/Manta#64]
**Is it a bug or a feature request?**

- [ ] It's a bug.
- [x] I'm requesting a new feature.

**Describe your issue**

I pretty much only care about "pending" invoices, for which I haven't been paid. It would be nice to split the invoices into 2 sections: "pending" and "paid"

**Comment by hql287** [comment]
This is a great idea and would be easy to implement, too. Thanks for the input. 
Would you like to take on this challenge? :)

**Comment by hql287** [comment]
A quick update on the UI for this feature. Maybe I'll ditch the table layout as there're too many columns already, and that doesn't include the pending/paid status. 

This a WIP but will wrap this up tomorrow. Let me know if you have any suggestions.

![mark as read](https://user-images.githubusercontent.com/2544327/33932003-560534fa-e024-11e7-8157-100d4c57ea07.gif)

**Comment by mathieudutour** [comment]
that looks super nice! Just so you know, I used a string for the status as there might be other statuses later on (perhaps even custom ones?). That's why I used a dropdown instead of the checkbox. This design doesn't account for that but maybe it can be changed later. Up to you :)

**Comment by mathieudutour** [comment]
while you are at it, it would be nice to show a context menu with those actions when right-clicking on an invoice. It doesn't feel really native without it

**Comment by hql287** [comment]
@mathieudutour Yes, I kind of understand why you chose the select but I think I'll keep it as Pending/Paid at the moment as these are the most common statuses. More options can be accessed via the menu or context menu like you suggested.

**Comment by hql287** [comment]
Btw, what would you put into the context menu? @mathieudutour

**Comment by mathieudutour** [comment]
just the 3 actions that are there as buttons for now. Only to make sure that _something_ happens when you right click: it's disturbing if nothing happens ;)

**Comment by hql287** [comment]
lol ok, noted!

**Comment by hql287** [comment]
Per your request, **Something** does happen!! 😄

<img width="514" alt="screen shot 2017-12-13 at 17 54 40" src="https://user-images.githubusercontent.com/2544327/33935500-becbd2d2-e02e-11e7-9351-98519dbe6f7f.png">

**Comment by hql287** [comment]
Guys, please refers to this issue https://github.com/hql287/Manta/issues/99 now as I decided to support more than just pending/paid.
