### ISSUE TITLE
Add support for decimal prices

### ISSUE THREAD

**Issue by TomasKostadinov** [hql287/Manta#67]
**Is it a bug or a feature request?**
- [x] It's a bug.
**Which version are you using?**
- [x] macOS
**Which is the version/distribution of the OS?**
macOS High Sierra

Please add support for decimal prices such as 7,99€; 20,23€. Currently the ',' just gets deleted.
That'd be really nice.

**Comment by philoushka** [comment]
I agree with this issue. The `.` is deleted during line item entry.

**Comment by TomasKostadinov** [comment]
Also it would be nice if both `.` and `,` get supported, maybe with an option in the settings sceen.
