### ISSUE TITLE
Allow preview before saving

### ISSUE THREAD

**Issue by peonmodel** [hql287/Manta#74]
**Is it a bug or a feature request?**

- [ ] It's a bug.
- [x] I'm requesting a new feature.

**Which version are you using?**

- [x] macOS
- [ ] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

I'm using macOS High Sierra

**Describe your issue**

Previewing cannot be done without first saving

**Comment by hql287** [comment]
Thanks! This's actually related to #7

**Comment by hql287** [comment]
Close due to inactivity and in favour of #7
