### ISSUE TITLE
Can't click any button, it grabs the window instead.

### ISSUE THREAD

**Issue by kozlown** [hql287/Manta#77]
**Is it a bug or a feature request?**

- [x] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [ ] macOS
- [ ] Windows
- [x] Linux

**Which is the version/distribution of the OS?**

Ubuntu Xenial

**Describe your issue**

I can't click any button, when I try to click it grabs the window instead.
![image](https://user-images.githubusercontent.com/8665643/33823323-019fb20c-de5b-11e7-8fd9-bf5b616690b8.png)

**Steps to replicate**

1. Build for linux with `yarn release:linux` or `yarn release` (for v1.0.0 branch), both have same behavior.
2. Try to click on a button ("Skip" or "NEXT") or anywhere else in the window.

**Comment by SkyzohKey** [comment]
Should be fixed once #72 is merged ;)

**Comment by hql287** [comment]
Merged #72
