### ISSUE TITLE
Cannot Interact with App on Windows

### ISSUE THREAD

**Issue by dream-encode** [hql287/Manta#80]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [x] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [ ] macOS
- [x] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**
Windows 10

**Describe your issue**
After initial install, app opens a "Tour" window.  There is a "Skip" link and a "Next" button.  Neither do anything.  

**Steps to replicate**
1. Install on Windows 10.
2. Try to click anything in the app.

**Comment by hql287** [comment]
Hi David, 

Thanks for reporting the issue. It's actually a known bug. You can try `Tab+Enter` to pass the welcome screen for now. The issue will be fixed in future version.

**Comment by crabmusket** [comment]
Same bug occurs on Linux (Ubuntu).

**Comment by hql287** [comment]
Same as https://github.com/hql287/Manta/issues/77
