### ISSUE TITLE
Allow printing

### ISSUE THREAD

**Issue by lachlanjc** [hql287/Manta#82]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [ ] It's a bug.
- [x] I'm requesting a new feature.

**Which version are you using?**

- [x] macOS
- [ ] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

I'm using macOS Sierra

**Describe your issue**

I'd like to be able to do <kbd>Cmd+P</kbd> on an invoice and print it out (such as to a PDF).

**Comment by hql287** [comment]
You can save it as a PDF, then print :)
