### ISSUE TITLE
Currencies are not sorted alphabetically 

### ISSUE THREAD

**Issue by shime** [hql287/Manta#84]
**Is it a bug or a feature request?**

- [X] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [X] macOS
- [ ] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

El Capitan

**Describe your issue**

When you go to `Settings` -> `App Settings` and try to find your currency under `Default Currency` dropdown, the currencies are not sorted alphabetically.

**Comment by hql287** [comment]
@shime You can start typing and it'll take you to the desired currency. The order of the currencies is the same in the Form and in the Settings as I use the same file. [I got it from here](https://gist.github.com/Fluidbyte/2973986), think it's based on the popularity of the currency. 

 This is not a bug btw so I'm closing this.

**Comment by shime** [comment]
Okay, it looks like they are sorted by code, after `USD`, `CAD` and `EUR` which are the most popular I guess. Maybe it would make sense to sort them by name since you're displaying that?

**Comment by hql287** [comment]
Sure, It does help less savvy users to navigate easier. Will work on this once I fixed the current bugs. Thanks!

**Comment by hql287** [comment]
Moved this to #89. 
Btw, it's fairly easy to do, would you like to take on the challenge? :)

**Comment by shime** [comment]
Cool, yes I would definitely like to take this one.

**Comment by hql287** [comment]
Awesome! Thanks!
