### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by erhankaradeniz** [hql287/Manta#87]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [ ] It's a bug.
- [x] I'm requesting a new feature.

**Which version are you using?**

- [x] macOS
- [ ] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

MacOS Sierra

**Describe your issue**

Would help if invoices could be translated into other languages, would love to help.

**Steps to replicate**

None needed.

**Comment by mathieudutour** [comment]
duplicates of #9, there are some more info over there
