### ISSUE TITLE
Better Tax Handling

### ISSUE THREAD

**Issue by hql287** [hql287/Manta#90]
I got a lot of requests on customizing taxes, both here and via email. So let's use this to keep track of all the requests related to Tax/Vat

- [ ] Add Tax Payer ID/Tax Registration Number
- [ ] Add `charged reversed` option See https://github.com/hql287/Manta/issues/63
- [ ] Option to set a default TAX value

Please let me know in the comments which others things you would like to include in the Tax/Vat section.

**Comment by hql287** [comment]
@mathieudutour Quick questions:

- Are there any other methods besides `charge_reverse` that are common in Europe? I'm considering checkbox/select at the moment. 
- If you chose `charge_reverse` as your tax method, how would you display it in the document? Do we need to say explicitly that this invoice is reverse charge applicable? Or simply just display the reverse charge amount? 

Can you provide an actual invoice that you used? 
Thanks!

**Comment by mathieudutour** [comment]
> Are there any other methods besides charge_reverse that are common in Europe? I'm considering checkbox/select at the moment.

I don't know of any other

> If you chose charge_reverse as your tax method, how would you display it in the document?

I'm showing it as
```
Subtotal: $X
VAT: charge reverse
Total: $X
```

**Comment by hql287** [comment]
Alright, Christmas really does mess up work, but this should come in handy :)

![Save tax settings as default](https://d2ffutrenqvap3.cloudfront.net/items/1F420Y2Q0r402e1o0e1A/save_default_tax_settings.gif?v=8edec68a)

**Comment by hql287** [comment]
Fixed with #109
