### ISSUE TITLE
Tour window has wrong position on dual monitor setup

### ISSUE THREAD

**Issue by ohyou** [hql287/Manta#91]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [x] It's a minor bug.

**Which version are you using?**

- [x] Linux

**Which is the version/distribution of the OS?**

`Linux 3.16.0-4-amd64 Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux`

**Describe your issue**

The Tour Window positions itself in the center of the "available screen area", which doesn't work properly with a dual monitor setup - it positions itself inbetween the two displays.

Screenshot: https://i.imgur.com/f463ama.png

**Steps to replicate**

1. Open the Manta for the first time

**Comment by hql287** [comment]
@ohyou Ahh, never thought of this! Thanks for reporting.

**Comment by hql287** [comment]
[This might be helpful](https://github.com/electron/electron/blob/master/docs/api/screen.md). Will work on this in the next release.
